// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWUhnjQo5i5zXqkrrhW_2m9zkqGgfjz38',
    appId: '1:565258340178:android:d849d20da2cd4fd5bddc8b',
    messagingSenderId: '565258340178',
    projectId: 'rent-my-boat-822a0',
    databaseURL:
        'https://rent-my-boat-822a0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rent-my-boat-822a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWB-4-G9DvEIOVvvCBAIvmE31MzPgCrgk',
    appId: '1:565258340178:ios:7e95cb07e276af43bddc8b',
    messagingSenderId: '565258340178',
    projectId: 'rent-my-boat-822a0',
    databaseURL:
        'https://rent-my-boat-822a0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rent-my-boat-822a0.appspot.com',
    iosClientId:
        '565258340178-k77ri53ip6qm4r8ooe5tq6ubhbarfjje.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentMyBoat',
  );
}
